StudentsPortal/App1/urls.py
from django.urls import path 
from . import views


urlpatterns = [
	path('register/', views.registration_page, name='register'),
	path('login/', views.login_page, name='login'),
	path('logout/', views.logout_user, name='logout'),
	path('', views.home, name='home'),
	path('MyProfile/', views.my_profile, name='my_profile'),
	path('OtherProfile/', views.other_profile, name='other_profile'),
	path('account/<int:id>/', views.account_view, name='view'),

	path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'), # AJAX
	path('ajax/load-cities2/', views.load_cities2, name='ajax_load_cities2'), # AJAX

	path('search/', views.account_search_view, name='search'),

	# logic to rememeber
	# path ('browserURL', views.function_defined_in_views.py, 'url_path_to_be_called_in_html')
]

StudentsPortal/StudentsPortal/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App1.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

StudentsPortal/App1/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.core.validators import RegexValidator
# from django.db.models.signals import post_save
# from django.dispatch import receiver

# Create your models here.

class Country(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class University(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Course(models.Model):
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class MyAccountManager(BaseUserManager):
	def create_user(self, email, username, password=None):
		if not email:
			raise ValueError("Users must have an Email Address!")
		if not username:
			raise ValueError("Users must have a Username")

		user = self.model(
			email=self.normalize_email(email),
			username=username,
		)
		user.set_password(password)
		user.save(using=self._db)
		return user
		
		
	def create_superuser(self, email, username, password):
		user = self.create_user(
			email = self.normalize_email(email),
			username=username,
			password=password,		
		)
		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.is_verified = True
		user.save(using=self._db)
		return user	

def get_profile_image_filepath(self, filename):
	return f'profile_pics/{self.pk}/{"profile_pic.png"}'


def get_default_profile_image():
	return "default_profile_pic.jpg"


class user(AbstractBaseUser):

	alphanumeric = RegexValidator(r'^[A-Za-z0-9_.]*$', 'Only Letters, Numbers, Underscores and Periods are allowed!')
	# Regex to match 10 to 12 digits only
	phonenumber = RegexValidator(r'^[0-9]{10,12}$', 'Only Numerical characters are allowed! (Must be 10-12Digits)')

	username		= models.CharField(max_length=30, unique=True, validators=[alphanumeric])
	email 			= models.EmailField(verbose_name="email", max_length=60, unique=True)
	phonenumber 	= models.CharField(max_length=30, unique=True, validators=[phonenumber])
	country 		= models.ForeignKey(Country, on_delete=models.SET_NULL, blank=True, null=True)
	university 		= models.ForeignKey(University, on_delete=models.SET_NULL, null=True)
	course			= models.ForeignKey(Course, on_delete=models.SET_NULL, blank=True, null=True)
	profile_pic 	= models.ImageField(null=True, blank=True, default=get_default_profile_image, upload_to=get_profile_image_filepath)
	bio 			= models.CharField(max_length=40, default="Hey there...", blank=True, null=True)
	date_joined 	= models.DateTimeField(verbose_name='date joined', auto_now_add=True)
	last_login		= models.DateTimeField(verbose_name='last login', auto_now=True)
	hide_email		= models.BooleanField(default=True)
	hide_phonenumber= models.BooleanField(default=True)
	is_active 		= models.BooleanField(default=True)
	is_admin 		= models.BooleanField(default=False)
	is_verified  	= models.BooleanField(default=False)
	is_staff 		= models.BooleanField(default=False)
	is_superuser 	= models.BooleanField(default=False)

	USERNAME_FIELD = 'username'
	REQUIRED_FIELDS = ['email']
	
	objects = MyAccountManager()

	def __str__(self):
		return self.username

	def get_profile_image_filename(self):
		return str(self.profile_pics)[str(self.profile_pics).index(f'profile_pics/{self.pk}/'):]

	def has_perm(self, perm, obj=None):
		return self.is_admin

	def has_module_perms(self, app_label):
		return True

# class Profile(models.Model):
# 	user 			= models.OneToOneField(user, on_delete=models.CASCADE)
# 	profile_pic 	= models.ImageField(null=True, default="default_profile_pic.jpg", upload_to="profile_pics")
# 	bio 			= models.CharField(max_length=40, default="Hey there...")

# 	def __str__(self):
# 		return self.user.email

# signals
# @receiver(post_save, sender=user)
# def create_user_profile(sender, instance, created, **kwargs):
# 	if created:
# 		Profile.objects.create(user=instance)

# @receiver(post_save, sender=user)
# def save_user_profile(sender, instance, **kwargs):
# 	instance.profile.save()

StudentsPortal/App1/forms.py
from django.contrib.auth.forms import UserCreationForm
#from django.contrib.auth.models import User
from django import forms
from .models import *

class create_user_form(UserCreationForm):
	class Meta:
		model = user
		fields = ['username', 'email', 'phonenumber', 'country', 'university', 'course']
		

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['university'].queryset = University.objects.none()
		self.fields['course'].queryset = Course.objects.none()

		if 'country' in self.data:
			try:
				country_id = int(self.data.get('country'))
				self.fields['university'].queryset =University.objects.filter(country_id=country_id).order_by('name')
			except (ValueError, TypeError):
				pass # invalid input from the client; ignore and fallback to empty University queryset
		elif self.instance.pk:
			self.fields['university'].queryset = self.instance.country.university_set.order_by('name')

		if 'university' in self.data:
			try:
				university_id = int(self.data.get('university'))
				self.fields['course'].queryset =Course.objects.filter(university_id=university_id).order_by('name')
			except (ValueError, TypeError):
				pass # invalid input from the client; ignore and fallback to empty University queryset
		elif self.instance.pk:
			self.fields['course'].queryset = self.instance.university.course_set.order_by('name')


# class user_profile(forms.ModelForm):
# 	class Meta:
# 		model = Profile
# 		fields = '__all__'
# 		exclude = ['user',]


class update_user_profile(forms.ModelForm):
	class Meta:
		model = user
		fields = ['username', 'phonenumber', 'country', 'profile_pic', 'bio', 'hide_email', 'hide_phonenumber']
		exclude = ['email', 'university', 'course', 'password1', 'password2']
		

StudentsPortal/App1/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import get_object_or_404

from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.conf import settings

# Create your views here.
from .forms import *
from .models import *
from .decorators import *

@unauthenticated_user
def registration_page(request):
	form = create_user_form()

	if request.method == 'POST':
		form = create_user_form(request.POST)
		if form.is_valid():
			form.save()
			user = form.cleaned_data.get('username') # allows to get only the username without any other details
			messages.success(request, 'Account successfully created for: ' + user)
			return redirect('login')

	context = {'form':form}
	return render(request, 'App1/register2.html', context)

@unauthenticated_user
def login_page(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(request, username=username, password=password)

		if user is not None:
			login(request, user)
			return redirect('home')
		else:
			messages.info(request, 'Incorrect Username or Password!')

	context = {}
	return render(request, 'App1/login.html', context)


def logout_user(request):
	logout(request)
	return redirect('login')


@login_required(login_url='login') # only allows users who are logged in with correct credentials
def home(request):
	return render(request, 'App1/dashboard.html')



# AJAX
def load_cities(request):
    country_id = request.GET.get('country_id')
    universities = University.objects.filter(country_id=country_id).all()
    return render(request, 'App1/university_dropdown_list_options.html', {'universities': universities})

def load_cities2(request):
    university_id = request.GET.get('university_id')
    courses = Course.objects.filter(university_id=university_id).all()
    return render(request, 'App1/course_dropdown_list_options.html', {'courses': courses})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)



@login_required(login_url='login') # only allows users who are logged in with correct credentials
def my_profile(request):
	user = request.user
	user_id = request.user.id
	form = update_user_profile(instance=user)

	if request.method == 'POST':
		form = update_user_profile(request.POST, request.FILES,instance=user)
		if form.is_valid:
			form.save()
			return redirect('my_profile')
			
			
	context = {'form':form}
	return render(request, 'App1/my_profile.html', context)


def other_profile(request):
	# context = {}
	
	return render(request, 'App1/other_profile.html')


@login_required(login_url='login') # only allows users who are logged in with correct credentials
def account_view(request, id):
	'''
	-LOGIC here is kind of tricky
		is_self(boolean)
			is_friend(boolean)
				-1: NO_REQUEST_SENT
				0: THEM_SENT_TO_YOU
				1: YOU_SENT_TO_THEM
	'''
	context = {}
	
	account = get_object_or_404(user, pk=id)
	
	# context = {}
	# user_id = kwargs.get("user_id")

	# try:
	# 	account = user.objects.get(pk=user_id)
	# except user.DoesNotExist:
	# 	return HttpResponse("That User doesn't Exist!")
	if account:
		context['id']: account.id
		context['username']: account.username
		context['email']: account.email
		context['profile_image']: account.profile_image.url
		context['hide_email']: account.hide_email
		context['hide_phonenumber']: account.hide_phonenumber

		# define state template variables
		is_self = False
		# is_friend = False

		user_id = request.user.id
		print(user_id)
		print(account.id)
		if user_id == account.id:
			is_self = True

		# context['user_id'] = user_id
		# context['is_self'] = is_self
		# context['is_friend'] = is_friend
		# context['BASE_URL'] = settings.BASE_URL
		# context = {'user_id': user_id, 'account_id': account.id}

	return render(request, "App1/other_profile.html", {'id':id, 'account':account, 'context': context})



def account_search_view(request, *args, **kwargs):
	context = {}

	if request.method == "GET":
		search_query = request.GET.get("q")
		if len(search_query) > 0:
			search_results = user.objects.filter(email__icontains=search_query).filter(username__icontains=search_query).distinct()
			# user = request.user
			accounts = []
			for account in search_results:
				accounts.append((account, False)) # You have no friends 
			context['accounts'] = accounts
	return render(request, "App1/search_results.html", context)




    

StudentsPortal/App1/templates/App1/city_dropdown_list_options.html
<option value="">---------</option>
{% for university in universities %}
<option value="{{ university.pk }}">{{ university.name }}</option>
{% endfor %}

StudentsPortal/App1/templates/App1/course_dropdown_list_options.html
<option id="" value="">Select-Course</option>
{% for course in courses %}
<option id="" value="{{ course.pk }}">{{ course.name }}</option>
{% endfor %}

StudentsPortal/App1/templates/App1/dashboard.html
{% extends 'App1/main.html' %}

{% block content %}


{% endblock %}

StudentsPortal/App1/templates/App1/footer.html
<style type="text/css">
    .mini-footer {
 background:#192027;
 text-align:center;
 padding:32px 0
}
.mini-footer p {
 margin:0;
 bottom: 0;
 line-height:26px;
 font-size:15px;
 color:#999
}
.mini-footer p a {
 color:#5867dd
}
.mini-footer p a:hover {
 color:#34bfa3
}
}
@media (max-width:991px) {
 .footer-menu {
  padding-left:0
 }
}

</style>
<div class="mini-footer">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="copyright-text">
            <p>© 2021
              <a href="#">WeAreLegion</a>. All rights reserved. Created by
              <a href="https://github.com/NickBwalley/">NickBwalley</a>
            </p>
          </div>

          <div class="go_top">
            <span class="icon-arrow-up"></span>
          </div>
        </div>
      </div>
    </div>
  </div>

StudentsPortal/App1/templates/App1/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Enter Username" class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Enter Password" class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages	%}
					<p id="messages">{{message}}</p>
				{% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

StudentsPortal/App1/templates/App1/main.html
{% load static %}
<!DOCTYPE html>
<head>
    <title>Student's Portal</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">

</head>
<body>
    {% include 'App1/navbar.html' %}

    {% block content %}
    

    {% endblock %}

    <hr>
    <footer>{% include 'App1/footer.html' %}</footer>

</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

StudentsPortal/App1/templates/App1/my_profile.html
{%  extends 'App1/main.html' %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}

<style>
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
</style>

<br>
<div class="row justify-content-center">
	<div class="col-md-5">
		<div class="card card-body">
		  
			<form method="POST" action="" enctype="multipart/form-data">
				{% csrf_token	%}

              <div class="form-group">
                <div class="col-lg-9">
                  <a class="btn btn-warning" href="{% url 'view' request.user.id %}"> &#8592; Back to Profile</a>               
                </div>
              </div>

				      <div class="form-group">
            		<div class="col-lg-9">
              			{{form.username|as_crispy_field }}
            		</div>
          		</div>

              <div class="form-group">
                <div class="col-lg-9">
                    {{form.phonenumber|as_crispy_field }}
                </div>
              </div>

              <div class="form-group">
                <div class="col-lg-9">
                    {{form.country|as_crispy_field }}
                </div>
              </div>

              <div class="form-group">
                <div class="col-lg-9">
                    {{form.profile_pic}}
                </div>
              </div>

              <div class="form-group">
                <div class="col-lg-9">
                    {{form.bio |as_crispy_field}}
                </div>
              </div>

              <div class="form-group">
                <div class="col-lg-9">
                    {{form.hide_email |as_crispy_field}}
                </div>
              </div>

              <div class="form-group">
                <div class="col-lg-9">
                    {{form.hide_phonenumber |as_crispy_field}}
                </div>
              </div>
     
                   		
			<input class="btn btn-success" type="submit" name="Update Information" value="Save Changes">
			</form>
		</div>
	</div>
</div>



{% endblock %}

StudentsPortal/App1/templates/App1/register2.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Students-Portal</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	
	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		#id_country{
			max-width: 200px;
			overflow-x: auto;
			text-overflow: ellipsis;
			overflow-wrap: break-word;
		}
		#id_university{
			max-width: 200px;
			overflow-x: auto;
			text-overflow: ellipsis;
			overflow-wrap: break-word;
		}
		#id_course{
			max-width: 200px;
			overflow-x: auto;
			text-overflow: ellipsis;
			overflow-wrap: break-word;
		}
		
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}"
					data-courses-url="{% url 'ajax_load_cities2' %}">
						{% csrf_token	%}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-phone"></i></span>
								<!--<input id="phone" name="phone" type="tel">-->
							</div>
							{{form.phonenumber}}
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-globe"></i></span>
							</div>
							{{form.country}}
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-university"></i></span>
							</div>
							{{form.university}}	
						</div>

						<div class="input-group mb-2" style="max-width: 250px;">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user-graduate"></i></span>
							</div>
							{{form.course}}	
						</div>
					

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>

				<span style="color:#ff0000;">{{form.errors}}</span>		

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Enter Username';
		form_fields[2].placeholder='Enter Email-Address';
		form_fields[3].placeholder='Enter Phonenumber';
		//form_fields[5].placeholder='Enter Country';
		// form_fields[6].placeholder='Enter University';
		//form_fields[7].placeholder='Enter Course';
		form_fields[4].placeholder='Enter Password';
		form_fields[5].placeholder='Confirm Password';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>

<!--AJAX LOAD COUNTRIES AND UNIVERSITIES-->

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_country").change(function () {
        const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const countryId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /App1/ajax/load-cities/ )
            data: {
                'country_id': countryId,      // add the country id to the GET parameters

            },

            success: function (data) {   // `data` is the return of the `load_cities` view function
            	console.log(data);
                $("#id_university").html(data);  // replace the contents of the university input with the data that came from the server
            }

        });

    });


</script>



<script>
    $("#id_university").change(function () {
        const url = $("#personForm").attr("data-courses-url");  // get the url of the `load_cities` view
        const universityId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /App1/ajax/load-cities/ )
            data: {
                'university_id': universityId,      // add the university id to the GET parameters
                
            },

            success: function (data) {   // `data` is the return of the `load_cities` view function
            	console.log(data);
                $("#id_course").html(data);  // replace the contents of the university input with the data that came from the server
                
            }

        });

    });


</script> 

	
</body>
</html>

StudentsPortal/App1/templates/App1/university_dropdown_list_options.html
<option value="">Select-University</option>
{% for university in universities %}
<option value="{{ university.pk }}">{{ university.name }}</option>
{% endfor %}